import { digest } from './hash.js';
import { prng } from './prng.js';
const permissions={full_culture:{message:true,fork:true,shared:true},no_communication:{message:false,fork:true,shared:true},stigmergy_only:{message:false,fork:false,shared:true},independent:{message:false,fork:false,shared:false}};
export class World {
 constructor({seed=1,condition='full_culture',agents=4,ticks=16}){this.seed=seed;this.condition=condition;this.ticks=ticks;this.random=prng(seed);this.agents=Array.from({length:agents},(_,i)=>({id:`agent-${i+1}`,memory:[],messages:[]}));this.artifacts=[];this.events=[];this.previousDigest='genesis';this.tick=0;}
 capabilities(){return permissions[this.condition];}
 visibleArtifacts(agent){return this.capabilities().shared?this.artifacts:this.artifacts.filter((a)=>a.owner===agent.id);}
 observe(agent){const capability=this.capabilities();return {artifacts:this.visibleArtifacts(agent).map(({id,title,status,parentId,owner})=>({id,title,status,parentId,owner})),messages:capability.message?agent.messages.splice(0):[],canMessage:capability.message,canFork:capability.fork,disturbanceHint:this.tick%3===2?'dependency perturbation approaching':'stable'};}
 record(type,payload){const event={id:`e-${this.events.length+1}`,tick:this.tick,type,payload,previousDigest:this.previousDigest};event.digest=digest(event);this.previousDigest=event.digest;this.events.push(event);return event;}
 resolve(agent,action){const allowed=new Set(['inspect','build','verify','message','fork','wait']);if(!action||!allowed.has(action.kind))return this.record('action_rejected',{agentId:agent.id,reason:'invalid_schema'});const cap=this.capabilities();if(action.kind==='message'&&!cap.message)return this.record('action_rejected',{agentId:agent.id,reason:'communication_disabled'});if(action.kind==='fork'&&!cap.fork)return this.record('action_rejected',{agentId:agent.id,reason:'forking_disabled'});if(action.kind==='build'){if(!action.title||!action.evidence)return this.record('action_rejected',{agentId:agent.id,reason:'missing_evidence'});const artifact={id:`a-${this.artifacts.length+1}`,owner:agent.id,title:action.title,evidence:action.evidence,parentId:null,status:'proposed',createdTick:this.tick};artifact.digest=digest(artifact);this.artifacts.push(artifact);return this.record('artifact_created',artifact);}if(action.kind==='fork'){const parent=this.visibleArtifacts(agent).find((a)=>a.id===action.parentId&&a.status==='verified');if(!parent||!action.title||!action.evidence)return this.record('action_rejected',{agentId:agent.id,reason:'invalid_parent_or_evidence'});const artifact={id:`a-${this.artifacts.length+1}`,owner:agent.id,title:action.title,evidence:action.evidence,parentId:parent.id,status:'proposed',createdTick:this.tick};artifact.digest=digest(artifact);this.artifacts.push(artifact);return this.record('artifact_forked',artifact);}if(action.kind==='verify'){const target=this.visibleArtifacts(agent).find((a)=>a.id===action.target&&a.status==='proposed');if(!target)return this.record('action_rejected',{agentId:agent.id,reason:'candidate_not_visible'});target.status='verified';target.verifiedBy=agent.id;target.verificationTick=this.tick;return this.record('artifact_verified',{artifactId:target.id,verifier:agent.id,evidenceDigest:target.digest});}if(action.kind==='message'){for(const recipient of this.agents.filter((other)=>other.id!==agent.id))recipient.messages.push({from:agent.id,body:action.body??''});return this.record('message_sent',{from:agent.id,body:action.body??''});}return this.record('action_observed',{agentId:agent.id,kind:action.kind});}
 async run(runtime){for(this.tick=0;this.tick<this.ticks;this.tick+=1){for(const agent of this.agents){const action=await runtime.decide({agentId:agent.id,tick:this.tick,observation:this.observe(agent),memory:agent.memory,condition:this.condition});this.resolve(agent,action);}this.record('world_tick',{entropy:this.random()});}return this;}
 snapshot(){return structuredClone({seed:this.seed,condition:this.condition,artifacts:this.artifacts,events:this.events,traceDigest:this.previousDigest});}
}